export const lines = {
    AEL:"Airport Express",
    TCL:"Tung Chung Line",
    TML:"Tuen Ma Line",
    EAL:"East Rail Line",
    TKL:"Tseung Kwan O",
}

export const stations = {
    HOK:"Hong Kong",
    KOW:"Kowloon",
    TSY:"Tsing Yi",
    AIR:"Airport",
    AWE:"AsiaWorld Expo",
    OLY:"Olympic",
    NAC:"Nam Cheong",
    LAK:"Lai King",
    SUN:"Sunny Bay",
    TUC:"Tung Chung",
    WKS:"Wu Kai Sha",
    MOS:"Ma On Shan",
    HEO:"Heng On",
    TSH:"Tai Shui Hang",
    SHM:"Shek Mun",
    CIO:"City One",
    STW:"Sha Tin Wai",
    CKT:"Che Kung Temple",
    TAW:"Tai Wai",
    HIK:"Hin Keng",
    DIH:"Diamond Hill",
    KAT:"Kai Tak",
    SUW:"Sung Wong Toi",
    TKW:"To Kwa Wan",
    HOM:"Ho Man Tin",
    HUH:"Hung Hom",
    ETS:"East Tsim Sha Tsui",
    AUS:"Austin",
    MEF:"Mei Foo",
    TWW:"Tsuen Wan West",
    KSR:"Kam Sheung Road",
    YUL:"Yuen Long",
    LOP:"Long Ping",
    TIS:"Tin Shui Wai",
    SIH:"Siu Hong",
    TUM:"Tuen Mun",
    NOP:"North Point",
    QUB:"Quarry Bay",
    YAT:"Yau Tong",
    TIK:"Tiu Keng Leng",
    TKO:"Tseung Kwan O",
    LHP:"LOHAS Park",
    HAH:"Hang Hau",
    POA:"Po Lam",
    ADM:"Admiralty",
    EXC:"Exhibition Centre",
    MKK:"Mong Kok East",
    KOT:"Kowloon Tong",
    SHT:"Sha Tin",
    FOT:"Fo Tan",
    RAC:"Racecourse",
    UNI:"University",
    TAP:"Tai Po Market",
    TWO:"Tai Wo",
    FAN:"Fanling",
    SHS:"Sheung Shui",
    LOW:"Lo Wu",
    LMC:"Lok Ma Chau",
}

